app/models.py
from . import db
from datetime import datetime
from flask_login import UserMixin
from werkzeug.security import generate_password_hash,check_password_hash
from . import login_manager

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key= True)
    username = db.Column(db.String(50),unique=True,nullable=False)
    email = db.Column(db.String(120),unique=True,nullable=False)
    image_file = db.Column(db.String(20),nullable =False, default='default.jpg')
    pass_secure = db.Column(db.String(100),nullable=False)
    posts = db.relationship('Post',backref= 'author',lazy=True)
    comments = db.relationship('Comment', backref='author', lazy= True)

    @property
    def password(self):
         raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f"User('{self.username}','{self.email}','{self.image_file}')"

class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key= True)
    title = db.Column(db.String(100),nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default= datetime.utcnow)
    summary = db.Column(db.String(100), nullable=False)
    content = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'), nullable=False)
    upvote = db.Column(db.Integer, nullable=False, default = 0)
    downvote = db.Column(db.Integer, nullable=False, default = 0)
    comments = db.relationship('Comment', backref='bpost', lazy=True)

    def __repr__(self):
        return f"Post('{self.title}','{self.date_posted}')"

class Comment(db.Model):
    __tablename__ ='comments'
    id = db.Column(db.Integer, primary_key=True)
    post_id = db.Column(db.Integer, db.ForeignKey('posts.id'), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    description = db.Column(db.Text, nullable=False)

    def __repr__(self):
        return f"Comment : id: {self.id} comment: {self.description}" 

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_simplemde import SimpleMDE

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
simple = SimpleMDE()

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    simple.init_app(app)

    # Will add the views and forms

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    from .post import post as post_blueprint
    app.register_blueprint(post_blueprint)

    return app 

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views,errors

app/main/views.py
from flask import Flask, render_template
from flask_bootstrap import Bootstrap
from flask_wtf import FlaskForm
from . import main
from app.models import Post,User
from flask_login import login_required

@main.route('/')
@main.route('/index')
@main.route('/index/<int:id>')
def index(id = None):
    if id:
        posts = Post.query.filter_by(id=id)
    else:
        posts = Post.query.all()
        title = 'Home'

    return render_template('index.html', posts=posts, title = title)

@main.route('/user/<uname>', methods = ['GET','POST'])
@login_required
def profile(uname):

    
    user = User.query.filter_by(username = uname).first()
    posts = Post.query.filter_by(user_id = user.id)
    

    return render_template("profile/profile.html",posts = posts ,user = user)

app/post/__init__.py
from flask import Blueprint

post = Blueprint('post',__name__)

from . import views,form

app/post/views.py
from flask import Blueprint, flash,redirect,url_for,render_template,abort,request
from .form import PostForm,CommentForm
from flask_login import login_required, current_user
from ..models import Post,Comment
from flask_wtf import FlaskForm
from .. import db
from . import post

@post.route('/post/new', methods =['GET', 'POST'])
@login_required
def newpost():
    form = PostForm()
  
    if form.validate_on_submit():
        mypost = Post(title=form.title.data, content = form.content.data, summary = form.summary.data, author = current_user)
        db.session.add(mypost)
        db.session.commit()
        form_title = form.title.data
        print("title",form_title)
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.index'))

    return render_template('post/newpost.html',post_form = form)

@post.route("/post/<int:post_id>", methods =['GET', 'POST'])
@login_required
def post(post_id):
 
    form = CommentForm()
    post = Post.query.get_or_404(post_id)
    comments = Comment.query.filter_by(post_id = post.id)
    date_posted = post.date_posted.strftime('%B %d, %Y')
    if form.validate_on_submit():
        comment = Comment(post_id = post_id, description =form.description.data, author = current_user)
        db.session.add(comment)
        db.session.commit()
        flash('Your comment was added!', 'success')
        return redirect(url_for('post.post', post_id = post_id))
    
    
    return render_template('post/post.html', title=post.title, post=post,comment_form = form ,comments = comments, date_posted = date_posted)

app/templates/base.html
{%block styles%}
<!-- Font Awesome -->
<link href="https://fonts.googleapis.com/css?family=Baloo+Bhai|Hind+Guntur&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
<!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.10.1/css/mdb.min.css" rel="stylesheet">
<link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">


<!--Importing the simple mde css and js files  -->
{{ simplemde.css}}
{{ simplemde.js }}
{%endblock%}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}
{%block content%}

{%endblock%}
<footer class="page-footer font-small cyan darken-3">

  <!-- Footer Elements -->
  <div class="container">

    <!-- Grid row-->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-12 py-5">
        <div class="mb-5 flex-center">

          <!-- Facebook -->
          <a class="fb-ic">
            <i class="fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!-- Twitter -->
          <a class="tw-ic">
            <i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!-- Google +-->
          <a class="gplus-ic">
            <i class="fab fa-google-plus-g fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!--Linkedin -->
          <a class="li-ic">
            <i class="fab fa-linkedin-in fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!--Instagram-->
          <a class="ins-ic">
            <i class="fab fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!--Pinterest-->
          <a class="pin-ic">
            <i class="fab fa-pinterest fa-lg white-text fa-2x"> </i>
          </a>
        </div>
      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row-->

  </div>
  <!-- Footer Elements -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="#"> Moses Wamakima</a>
  </div>
  <!-- Copyright -->

</footer>

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}
    <h1>WHOOOPS we can't find that page</h1>
{% endblock %} 

app/templates/index.html
{% extends 'base.html' %}

{% block content %}

<header class="jumbotron topper">
  <H1 class="welcome">Welcome</H1>
  <h3>To my Blog</h3>
</header>
<div class="container posts">
  <div class="row">

    <div class="col-md-2"></div>
    <div class="col-md-8">
      {%for post in posts%}

      <div class="card card-cascade wider">

        <!-- Card image -->
        <div class="view view-cascade gradient-card-header">

          <!-- Title -->
          <h2 class="card-header-title mb-3">{{post.title}}</h2>
          <!-- Text -->
          <p class="mb-0"><i class="time fas fa-calendar mr-2"></i>{{post.date_posted}}</p>

        </div>

        <!-- Card content -->
        <div class="card-body card-body-cascade text-center">

          <!-- Text -->
          <p class="card-text">{{post.summary}}</p>
          <!-- Link -->
          <a href="{{url_for('post.post',post_id=post.id)}}" class="linker d-flex flex-row-reverse p-2">
            <h5 class="waves-effect waves-light">Read more<i class="fas fa-angle-double-right ml-2"></i></h5>
          </a>

        </div>
        <!-- Card content -->

      </div>
      {% endfor%}
    </div>
    <div class="col-md-2"></div>

  </div>
</div>
{% endblock %}

app/templates/navbar.html
<nav class="navs mb-1 navbar bg-white sticky-top navbar-expand-lg">
  <a class="navbar-brand" href="{{url_for('main.index')}}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-555"
    aria-controls="navbarSupportedContent-555" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent-555">
    <ul class=" navbar-nav mr-auto">
        {% if current_user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('post.newpost')}}">Write blog</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('auth.logout')}}">Log out</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('auth.login')}}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('auth.signup')}}">Signup</a>
      </li>
      {%endif%}
    </ul>
    <ul class="navbar-nav ml-auto nav-flex-icons">
      {% if current_user.is_authenticated %}
      <li class="nav-item avatar">
        <a class="nav-link p-0" href="{{url_for('main.profile',uname=current_user.username)}}">
          <img src="/static/default.jpg" class="rounded-circle z-depth-0"
            alt="avatar image" height="35">
        </a>
      </li>
      {% else %}
      <li class="nav-item avatar">
        <a class="nav-link p-0" href="#">
          <img src="https://mdbootstrap.com/img/Photos/Avatars/avatar-5.jpg" class="rounded-circle z-depth-0"
            alt="avatar image" height="35">
        </a>
      </li>
      {%endif%}
    </ul>
  </div>
</nav>

app/templates/post/newpost.html
{%extends 'base.html'%}

{%import 'bootstrap/wtf.html' as wtf%}

{%block title%}
New
{%endblock%}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <div class="card">
        {{ wtf.quick_form(post_form) }}
        {{simplemde.load}}
      </div>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

{%endblock%}

app/templates/post/post.html
{%extends 'base.html'%}

{%import 'bootstrap/wtf.html' as wtf%}
{%block content%}
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <div>
        <div class="card">
          <div class="card-body">
            <h2>{{post.title}}</h2>
            <h4>{{post.summary}}</h4>
            <p>{{post.content}}</p>
          </div>
        </div>
      </div>
      {{wtf.quick_form(comment_form)}}
      {%for comment in comments%}
      <div class="card">
        <div class="card-body">
          <p>{{comment.description}}</p>
        </div>
      </div>
      {% endfor%}
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

{%endblock%}

app/templates/profile/profile.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}

<div class="container">
  <div class="row">
    <div class="profile col-md-4">
      <h3> {{user.username| capitalize}} </h3>
      {% if user.image_file %}
      <img src="{{url_for('static',filename=user.image_file)}}" alt="" class="img-thumbnail">
      {%else%}
      <p>No profile picture</p>
      {% endif %}
    </div>
    <div class="pitches col-md-8">
      {% for post in posts %}
      <div class="card">
        <h1>{{post.title}}</h1>
        <p>{{post.body}}</p>
      </div>
      {%endfor%}
    </div>
  </div>
</div>
{% endblock %}